apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: traefik-v2
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: crowdsec-bouncer-traefik-plugin@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              name: web
  