image:
  tag: v3.7.1

logs:
  general:
    level: DEBUG
  access:
    enabled: true
    format: json
    fields:
      headers: 
        defaultmode: keep

experimental:
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.6.0"
