http:
  routers:
    whoami-http:
      rule: "Host(`localhost`)"
      service: whoami
      middlewares:
        - crowdsec@file

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami:80
  
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: DEBUG
          crowdsecMode: stream
          crowdsecLapiKey: 40796d93c2958f9e58345514e67740e5=
          captchaProvider: hcaptcha
          captchaSiteKey: 94476319-6b8e-44a8-9d13-4ef1de9b3001
          captchaSecretKey: ES_eac317320a9f494d83c5e0267f2284ed
          captchaGracePeriodSeconds: 20
          crowdsecAppsecEnabled: true
