image:
  tag: v2.9.10

logs:
  general:
    level: DEBUG
  access:
    enabled: true
    fields:
      headers: 
        defaultmode: keep

experimental:
  plugins:
    enabled: true

additionalArguments:
  - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
  - "--experimental.plugins.bouncer.version=v1.1.11"
